/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controler.ChessGameControler_sockets;
import controler.I_ChessGameControlers;
import controler.controlerLocal.ChessGameControler_local;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import model.Couleur;
import model.observable.ChessGame;
import socket.AbstractSocket;
import socket.SocketClient;
import socket.SocketInformations;
import socket.SocketServeur;

/**
 *
 * @author Tristan
 */
public class ChessGameAccueil extends javax.swing.JFrame {

    SocketInformations socketInformations;

    /**
     * Creates new form ChessGameAccueil
     */
    public ChessGameAccueil(SocketInformations i) {
        initComponents();
        socketInformations = i;
        jLabel_attenteClient.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel_ip = new javax.swing.JLabel();
        jLabel_port = new javax.swing.JLabel();
        jTextField_ip = new javax.swing.JTextField();
        jTextField_port = new javax.swing.JTextField();
        jButton_jeuReseau = new javax.swing.JButton();
        jButton_jeuLocal = new javax.swing.JButton();
        jButton_connexion = new javax.swing.JButton();
        JRadio_Serveur = new javax.swing.JRadioButton();
        jRadio_client = new javax.swing.JRadioButton();
        jLabel_attenteClient = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIENVENUE");

        jLabel_ip.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_ip.setLabelFor(jTextField_ip);
        jLabel_ip.setText("Adresse IP");
        jLabel_ip.setEnabled(false);

        jLabel_port.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel_port.setLabelFor(jTextField_port);
        jLabel_port.setText("Port");
        jLabel_port.setEnabled(false);

        jTextField_ip.setText("127.0.0.1");
        jTextField_ip.setToolTipText("");
        jTextField_ip.setEnabled(false);
        jTextField_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ipActionPerformed(evt);
            }
        });

        jTextField_port.setText("2009");
        jTextField_port.setEnabled(false);

        jButton_jeuReseau.setText("Jeu Reseau");
        jButton_jeuReseau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_jeuReseauActionPerformed(evt);
            }
        });

        jButton_jeuLocal.setText("Jeu Local");
        jButton_jeuLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_jeuLocalActionPerformed(evt);
            }
        });

        jButton_connexion.setText("Se connecter");
        jButton_connexion.setEnabled(false);
        jButton_connexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_connexionActionPerformed(evt);
            }
        });

        buttonGroup1.add(JRadio_Serveur);
        JRadio_Serveur.setText("Serveur");
        JRadio_Serveur.setEnabled(false);
        JRadio_Serveur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JRadio_ServeurActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_client);
        jRadio_client.setText("Client");
        jRadio_client.setEnabled(false);
        jRadio_client.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_clientActionPerformed(evt);
            }
        });

        jLabel_attenteClient.setText("En attente d'un client...");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(0, 116, Short.MAX_VALUE)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jButton_jeuLocal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(layout.createSequentialGroup()
                                        .add(JRadio_Serveur)
                                        .add(20, 20, 20))
                                    .add(jLabel_port)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(0, 0, Short.MAX_VALUE)
                                .add(jLabel_ip)))
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(39, 39, 39)
                                .add(jButton_jeuReseau, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(layout.createSequentialGroup()
                                .add(18, 18, 18)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jTextField_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextField_ip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                        .add(107, 107, 107))))
            .add(layout.createSequentialGroup()
                .add(282, 282, 282)
                .add(jRadio_client)
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jButton_connexion)
                        .add(199, 199, 199))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(jLabel_attenteClient)
                        .add(187, 187, 187))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton_jeuReseau, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton_jeuLocal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(JRadio_Serveur)
                    .add(jRadio_client))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel_ip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField_ip, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField_port, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jButton_connexion)
                .add(18, 18, 18)
                .add(jLabel_attenteClient)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ipActionPerformed

    private void jButton_jeuReseauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_jeuReseauActionPerformed
        jLabel_ip.setEnabled(true);
        jLabel_port.setEnabled(true);
        JRadio_Serveur.setEnabled(true);
        jRadio_client.setEnabled(true);
    }//GEN-LAST:event_jButton_jeuReseauActionPerformed

    private void jButton_jeuLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_jeuLocalActionPerformed

        socketInformations.isJeuReseau = false;
        socketInformations.choixOk = true;

        this.dispose();
    }//GEN-LAST:event_jButton_jeuLocalActionPerformed

    private void jButton_connexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_connexionActionPerformed
        socketInformations.ip = jTextField_ip.getText();
        socketInformations.port = Integer.parseInt(jTextField_port.getText());
        socketInformations.isJeuReseau = true;
        socketInformations.isServeur = JRadio_Serveur.isSelected();
        socketInformations.choixOk = true;
        this.dispose();
    }//GEN-LAST:event_jButton_connexionActionPerformed

    private void JRadio_ServeurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JRadio_ServeurActionPerformed
        jButton_connexion.setEnabled(true);
        jLabel_port.setEnabled(true);
        jTextField_port.setEnabled(true);
        jTextField_ip.setEnabled(false);
        jLabel_ip.setEnabled(false);
    }//GEN-LAST:event_JRadio_ServeurActionPerformed

    private void jRadio_clientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_clientActionPerformed
        jButton_connexion.setEnabled(true);
        jLabel_port.setEnabled(true);
        jTextField_port.setEnabled(true);
        jTextField_ip.setEnabled(true);
        jLabel_ip.setEnabled(true);
    }//GEN-LAST:event_jRadio_clientActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton JRadio_Serveur;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JButton jButton_connexion;
    private javax.swing.JButton jButton_jeuLocal;
    private javax.swing.JButton jButton_jeuReseau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_attenteClient;
    private javax.swing.JLabel jLabel_ip;
    private javax.swing.JLabel jLabel_port;
    private javax.swing.JRadioButton jRadio_client;
    private javax.swing.JTextField jTextField_ip;
    private javax.swing.JTextField jTextField_port;
    // End of variables declaration//GEN-END:variables
}
